services:
  postfix:
    image: glavich/docker-postfix:latest
    container_name: Postfix-Server
    environment:
      - DKIM_DOMAIN=koruapp.it
      - DKIM_SELECTOR=mail
    volumes:
      - ./keys/mail.private:/etc/opendkim/keys/mail.private
    ports:
      - "127.0.0.1:25:25"
