FROM debian:bullseye-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libc6 \
    libgcc-s1 \
    libstdc++6 \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /app/logs

COPY ./build/service /app/service
COPY ./.env.docker /app/.env

RUN chmod +x /app/service

CMD ["/app/service"]
