FROM alpine:3.20.3

# Installare glibc su Alpine
RUN apk add --no-cache \
    binutils \
    curl \
    gcc \
    libgcc \
    libstdc++ \
    && curl -Lo /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub \
    && curl -Lo /tmp/glibc.apk https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.35-r1/glibc-2.35-r1.apk \
    && apk add --no-cache /tmp/glibc.apk \
    && rm /tmp/glibc.apk

RUN mkdir /lib64

# RUN ls /lib64/ld-linux-x86-64.so.2 || echo "ld-linux-x86-64.so.2 non trovato"

RUN ln -s /lib/ld-linux-x86-64.so.2 /lib64/ld-linux-x86-64.so.2

RUN find / -name libgcc_s.so.1

WORKDIR /app

COPY ./build/service /app/service
COPY ../../../.env /app/.env

RUN chmod +x /app/service

ENV LD_LIBRARY_PATH="/usr/lib:/lib:/usr/local/lib"

RUN ldd /app/service

CMD ["/app/service"]