FROM alpine:3.20.3

WORKDIR /app

RUN apk add --no-cache \
    binutils \
    curl \
    gcc \
    libgcc \
    libstdc++ \
    file \
    bash \
    && curl -Lo /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub \
    && curl -Lo /tmp/glibc.apk https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.35-r1/glibc-2.35-r1.apk \
    && apk add --no-cache /tmp/glibc.apk \
    && rm /tmp/glibc.apk

RUN ls -l /lib/ld-linux-aarch64.so.1 || echo "ld-linux-aarch64.so.1 non trovato"

COPY ./build/service /app/service
COPY ../../../.env /app/.env

# Verifica se il binario è presente e controlla i permessi e l'architettura
RUN chmod +x /app/service && \
    file /app/service && \
    ls -l /app/service

CMD ["/app/service"]
