name: koru-tech

services:
  db-dev:
    container_name: PostgreSQL-Database-DEV
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DEV_DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "127.0.0.1:${DEV_DB_PORT}:${DEV_DB_PORT}"
    command: postgres -c 'port=${DEV_DB_PORT}'
    networks:
      - koru-network

  db-prod:
    container_name: PostgreSQL-Database-PROD
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${PROD_DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "127.0.0.1:${PROD_DB_PORT}:${PROD_DB_PORT}"
    command: postgres -c 'port=${PROD_DB_PORT}'
    networks:
      - koru-network

  pgadmin:
    container_name: PostgreSQL-Admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - koru-network
    depends_on:
      - db-dev
      - db-prod

  portainer:
    container_name: Portainer
    image: portainer/portainer-ce
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "${PORTAINER_PORT}:9000"
    networks:
      - koru-network
    restart: always

  rabbitmq-dev:
    container_name: RabbitMQ-DEV
    image: rabbitmq:3-management
    ports:
      - "127.0.0.1:${DEV_RABBITMQ_SERVICE_PORT}:${DEV_RABBITMQ_SERVICE_PORT}" # service port
      - "${DEV_RABBITMQ_UI_PORT}:15672" # UI port
    networks:
      - koru-network
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${DEV_RABBITMQ_PASSWORD}
    volumes:
      - ./support/rabbitmq/rabbitmq.dev.conf:/etc/rabbitmq/rabbitmq.conf

  rabbitmq-prod:
    container_name: RabbitMQ-PROD
    image: rabbitmq:3-management
    ports:
      - "127.0.0.1:${PROD_RABBITMQ_SERVICE_PORT}:${PROD_RABBITMQ_SERVICE_PORT}" # service port
      - "${PROD_RABBITMQ_UI_PORT}:15672" # UI port
    networks:
      - koru-network
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${PROD_RABBITMQ_PASSWORD}
    volumes:
      - ./support/rabbitmq/rabbitmq.prod.conf:/etc/rabbitmq/rabbitmq.conf

  postfix:
    container_name: Postfix-Server
    image: glavich/docker-postfix:latest
    environment:
      - DKIM_DOMAIN=${MAIL_DOMAIN}
      - DKIM_SELECTOR=${MAIL_SELECTOR}
    volumes:
      - ./support/postfix/${MAIL_SELECTOR}.private:/etc/opendkim/keys/${MAIL_SELECTOR}.private
    ports:
      - "127.0.0.1:${MAIL_PORT}:25"

volumes:
  portainer_data:

networks:
  koru-network:
    external: true
