name: koru-backend-prod-core

services:
  api-gateway:
    container_name: API-Gateway
    image: koru-core-api-gateway:latest
    environment:
      - ENV_PATH=/service/.env
    ports:
      - "9100:9100"
    networks:
      - koru-network

networks:
  koru-network:
    external: true