name: koru-prod-tech

services:
  db:
    container_name: PostgreSQL-Database
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    command: postgres -c 'port=${DB_PORT}'
    networks:
      - koru-network

  pgadmin:
    container_name: PostgreSQL-Admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - koru-network
    depends_on:
      - db

  rabbitmq:
    container_name: RabbitMQ
    image: rabbitmq:3-management
    ports:
      - "${RABBITMQ_SERVICE_PORT}:${RABBITMQ_SERVICE_PORT}"  # service port
      - "${RABBITMQ_UI_PORT}:15672" # UI port
    networks:
      - koru-network
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - ../support/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  portainer:
      container_name: Portainer
      image: portainer/portainer-ce
      command: -H unix:///var/run/docker.sock
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data
      ports:
        - "${PORTAINER_PORT}:9000"
        - "9000:9000"
      networks:
        - koru-network
      restart: always

volumes:
  portainer_data:

networks:
  koru-network:
    external: true
