name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'DEPLOY')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create SSH directory
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Add remote server to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.REMOTE_SERVER }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy code to server
        run: |
          scp -r ./docker ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_SERVER }}:/var/www/helvetica-test/docker
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
